### ISSUE TITLE
bsc light client on map Some of the details

### ISSUE THREAD

**Issue by Jimmie3** [mapprotocol/map-contracts#11]
1.Block difficulty is 1 or 2,InTurn is 2 else is 1 (https://github.com/bnb-chain/bsc/blob/master/consensus/parlia/parlia.go line 582 - 590);
2. function maxCanVerifyNum()  is the  lastSyncedBlock + epochNum +validators[lastSyncedBlock].length / 40 
  (https://docs.bnbchain.org/docs/learn/consensus)

**Comment by philllau** [comment]
#15
